@startuml

interface Handler {
    SetNext(Handler)
    handle(Request)
}

Handler <|.  BaseHandler
Handler <-  "next" BaseHandler

BaseHandler <|-- ConcreteHandler1
BaseHandler <|- ConcreteHandler2


@enduml